# Generated by Django 3.0.3 on 2020-02-20 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthcbUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='O email será usado como parte das credenciais para acesso ao sistema', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin?')),
                ('first_name', models.CharField(blank=True, max_length=60, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='Sobrenome')),
                ('username', models.CharField(blank=True, max_length=60, verbose_name='Username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do registro')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Grupo')),
                ('user_permissions', models.ManyToManyField(blank=True, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
