# Generated by Django 3.0.3 on 2020-02-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcbuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin?'),
        ),
    ]
