# Generated by Django 3.0.3 on 2020-02-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcb', '0002_auto_20200219_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcbuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
