# Generated by Django 3.0.3 on 2020-02-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('authcb', '0002_auto_20200214_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcbuser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Grupo'),
        ),
    ]
