# Generated by Django 3.0.3 on 2020-02-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcb', '0004_authcbuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcbuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='authcbuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='authcbuser',
            name='username',
            field=models.CharField(blank=True, max_length=60, verbose_name='Username'),
        ),
    ]
