# Generated by Django 3.0.3 on 2020-02-17 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authcb', '0005_auto_20200214_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcbuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do registro'),
        ),
    ]
