# Generated by Django 3.0.3 on 2020-02-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='name',
            field=models.CharField(default='Nome Completo', max_length=70, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
    ]
