# Generated by Django 3.0.3 on 2020-02-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reseller_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseller',
            options={'verbose_name': 'Revendedor', 'verbose_name_plural': 'Revendedores'},
        ),
        migrations.RenameField(
            model_name='reseller',
            old_name='name',
            new_name='full_name',
        ),
    ]
