# Generated by Django 3.0.3 on 2020-02-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackDebit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Percentagem do cashback')),
                ('cashback_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago')], default='PENDING', max_length=8, verbose_name='Status')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='debit', to='purchase.Purchase')),
            ],
            options={
                'verbose_name': 'Cashback Débito',
                'verbose_name_plural': 'Cashback Débitos',
            },
        ),
        migrations.CreateModel(
            name='CashbackRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('end_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Porcentagem do Cashback')),
            ],
            options={
                'verbose_name': 'Intervalo de valores',
                'verbose_name_plural': 'Intervalos de valores',
                'ordering': ['-start_value'],
            },
        ),
        migrations.CreateModel(
            name='CashbackPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateField(verbose_name='Data do pagamento')),
                ('cashbak_debit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cashback_payments', to='cashback.CashbackDebit')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_refunds', to='purchase.Purchase')),
            ],
            options={
                'verbose_name': 'Cashback Pagamento',
                'verbose_name_plural': 'Cashback Pagamentos',
            },
        ),
    ]
