# Generated by Django 3.0.3 on 2020-02-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cashback_percent',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_purchase',
            field=models.DateField(verbose_name='Data da compra'),
        ),
    ]
