# Generated by Django 3.0.3 on 2020-02-21 22:22

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
        ('purchase', '0002_approvedcpf_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedcpf',
            name='cpf',
            field=localflavor.br.models.BRCPFField(default=1, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approvedcpf',
            name='reseller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reseller.Reseller'),
        ),
    ]
