# Generated by Django 3.0.3 on 2020-06-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20200221_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('EM_AVALIACAO', 'Em avaliação'), ('APROVADO', 'Aprovado')], default='EM_AVALIACAO', max_length=16, verbose_name='Status'),
        ),
    ]
