# Generated by Django 3.0.3 on 2020-02-20 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authcb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('authcbuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('full_name', models.CharField(max_length=70, verbose_name='Nome Completo')),
            ],
            options={
                'verbose_name': 'Revendedor',
                'verbose_name_plural': 'Revendedores',
            },
            bases=('authcb.authcbuser',),
        ),
    ]
